CREATE TABLE `user` (
  `user_id` int NOT NULL AUTO_INCREMENT COMMENT '用户唯一标识',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password_hash` varchar(255) NOT NULL COMMENT 'PBKDF2密码哈希',
  `salt` varchar(64) NOT NULL COMMENT 'PBKDF2盐值(32字节hex)',
  `iterations` int NOT NULL DEFAULT 100000 COMMENT 'PBKDF2迭代次数',
  `email` varchar(100) NOT NULL COMMENT '电子邮箱',
  `phone` varchar(20) DEFAULT NULL COMMENT '手机号码',
  `full_name` varchar(100) DEFAULT NULL COMMENT '真实姓名',
  `gender` tinyint DEFAULT 0 COMMENT '性别(0-未知,1-男,2-女)',
  `birthday` date DEFAULT NULL COMMENT '出生日期',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像URL',
  `address` varchar(255) DEFAULT NULL COMMENT '常住地址',
  `preference_type` varchar(255) DEFAULT NULL COMMENT '偏好旅游类型',
  `preference_destination` varchar(255) DEFAULT NULL COMMENT '偏好目的地',
  `budget_range` varchar(50) DEFAULT NULL COMMENT '预算范围',
  `last_login_time` datetime DEFAULT NULL COMMENT '最后登录时间',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态(0-禁用,1-正常)',
  `register_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_username` (`username`),
  UNIQUE KEY `uk_email` (`email`),
  UNIQUE KEY `uk_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';